In [31]:
import pandas as pd

## Read datasets

In [32]:
# Dataset 1
student_academic_performance_ds = pd.read_csv("data/students_academic_performance_dataset.csv")
student_academic_performance_ds.head()

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,15,16,2,20,Yes,Good,Under-7,M
1,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,20,20,3,25,Yes,Good,Under-7,M
2,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,10,7,0,30,No,Bad,Above-7,L
3,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,30,25,5,35,No,Bad,Above-7,L
4,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,40,50,12,50,No,Bad,Above-7,M

In [33]:
# Dataset 2
student_performance_ds = pd.read_csv("data/student_performance_dataset.csv", sep=";")
student_performance_ds.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [34]:
# Dataset 3.1
open_university_learning_analytics_assessments_ds = pd.read_csv("data/open_university_learning_analytics_dataset/assessments.csv")
open_university_learning_analytics_assessments_ds.head()

  code_module code_presentation  id_assessment assessment_type date  weight
0         AAA             2013J           1752             TMA   19    10.0
1         AAA             2013J           1753             TMA   54    20.0
2         AAA             2013J           1754             TMA  117    20.0
3         AAA             2013J           1755             TMA  166    20.0
4         AAA             2013J           1756             TMA  215    30.0

In [35]:
# Dataset 3.2
open_university_learning_analytics_courses_ds = pd.read_csv("data/open_university_learning_analytics_dataset/courses.csv")
open_university_learning_analytics_courses_ds.head()

  code_module code_presentation  module_presentation_length
0         AAA             2013J                         268
1         AAA             2014J                         269
2         BBB             2013J                         268
3         BBB             2014J                         262
4         BBB             2013B                         240

In [36]:
# Dataset 3.3
open_university_learning_analytics_student_assessment_ds = pd.read_csv("data/open_university_learning_analytics_dataset/studentAssessment.csv")
open_university_learning_analytics_student_assessment_ds.head()

   id_assessment  id_student  date_submitted  is_banked score
0           1752       11391              18          0    78
1           1752       28400              22          0    70
2           1752       31604              17          0    72
3           1752       32885              26          0    69
4           1752       38053              19          0    79

In [37]:
# Dataset 3.4
open_university_learning_analytics_student_info_ds = pd.read_csv("data/open_university_learning_analytics_dataset/studentInfo.csv")
open_university_learning_analytics_student_info_ds.head()

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass

In [38]:
# Dataset 3.5
open_university_learning_analytics_student_registration_ds = pd.read_csv("data/open_university_learning_analytics_dataset/studentRegistration.csv")
open_university_learning_analytics_student_registration_ds.head()

,code_module,code_presentation,id_student,date_registration,date_unregistration
0,AAA,2013J,11391,-159,?
1,AAA,2013J,28400,-53,?
2,AAA,2013J,30268,-92,12
3,AAA,2013J,31604,-52,?
4,AAA,2013J,32885,-176,?

In [39]:
# Dataset 3.6
open_university_learning_analytics_student_vle_ds = pd.read_csv("data/open_university_learning_analytics_dataset/studentVLE.csv")
open_university_learning_analytics_student_vle_ds.head()

  code_module code_presentation  id_student  id_site  date  sum_click
0         AAA             2013J       28400   546652   -10          4
1         AAA             2013J       28400   546652   -10          1
2         AAA             2013J       28400   546652   -10          1
3         AAA             2013J       28400   546614   -10         11
4         AAA             2013J       28400   546714   -10          1

In [40]:
# Dataset 3.7
open_university_learning_analytics_vle_ds = pd.read_csv("data/open_university_learning_analytics_dataset/vle.csv")
open_university_learning_analytics_vle_ds.head()

   id_site code_module code_presentation activity_type week_from week_to
0   546943         AAA             2013J      resource         ?       ?
1   546712         AAA             2013J     oucontent         ?       ?
2   546998         AAA             2013J      resource         ?       ?
3   546888         AAA             2013J           url         ?       ?
4   547035         AAA             2013J      resource         ?       ?

### ✅ With the nature of available data and the task given, decided to move with Open University Learning Analytics Dataset

## Pre-Processing

#### 1. Check null value counts in each dataframe

In [41]:
datasets = {
    "assessments": open_university_learning_analytics_assessments_ds,
    "courses": open_university_learning_analytics_courses_ds,
    "studentInfo": open_university_learning_analytics_student_info_ds,
    "studentRegistration": open_university_learning_analytics_student_registration_ds,
    "studentAssessment": open_university_learning_analytics_student_assessment_ds,
    "studentVle": open_university_learning_analytics_student_vle_ds,
    "vle": open_university_learning_analytics_vle_ds
}

for name, df in datasets.items():
    print(f"\n{name} missing values:")
    print(df.isnull().sum())

assessments missing values:
code_module          0
code_presentation    0
id_assessment        0
assessment_type      0
date                 0
weight               0
dtype: int64

courses missing values:
code_module                   0
code_presentation             0
module_presentation_length    0
dtype: int64

studentInfo missing values:
code_module             0
code_presentation       0
id_student              0
gender                  0
region                  0
highest_education       0
imd_band                0
age_band                0
num_of_prev_attempts    0
studied_credits         0
disability              0
final_result            0
dtype: int64

studentRegistration missing values:
code_module            0
code_presentation      0
id_student             0
date_registration      0
date_unregistration    0
dtype: int64

studentAssessment missing values:
id_assessment     0
id_student        0
date_submitted    0
is_banked         0
score             0
dtype: int64

studentVle missing values:
code_module          0
code_presentation    0
id_student           0
id_site              0
date                 0
sum_click            0
dtype: int64

vle missing values:
id_site              0
code_module          0
code_presentation    0
activity_type        0
week_from            0
week_to              0
dtype: int64

#### 2. Merge assessments and student assessment data sets

In [42]:
open_university_learning_analytics_student_assessment_ds.dtypes

id_assessment      int64
id_student         int64
date_submitted     int64
is_banked          int64
score             object
dtype: object

In [43]:
open_university_learning_analytics_assessments_ds.dtypes

code_module           object
code_presentation     object
id_assessment          int64
assessment_type       object
date                  object
weight               float64
dtype: object

In [44]:
# Change data type in student assessment dataset object -> numeric
open_university_learning_analytics_student_assessment_ds["score"] = pd.to_numeric(open_university_learning_analytics_student_assessment_ds["score"], errors="coerce").fillna(0)
open_university_learning_analytics_student_assessment_ds.dtypes

id_assessment       int64
id_student          int64
date_submitted      int64
is_banked           int64
score             float64
dtype: object

In [45]:
# Merge Assessment Dataset into Student Assessment Dataset
open_university_learning_analytics_student_assessment_ds = open_university_learning_analytics_student_assessment_ds.merge(open_university_learning_analytics_assessments_ds, on="id_assessment", how="left")
open_university_learning_analytics_student_assessment_ds.head()

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight
0,1752,11391,18,0,78.0,AAA,2013J,TMA,19,10.0
1,1752,28400,22,0,70.0,AAA,2013J,TMA,19,10.0
2,1752,31604,17,0,72.0,AAA,2013J,TMA,19,10.0
3,1752,32885,26,0,69.0,AAA,2013J,TMA,19,10.0
4,1752,38053,19,0,79.0,AAA,2013J,TMA,19,10.0

In [46]:
# Create weighted score column
open_university_learning_analytics_student_assessment_ds["weighted_score"] = (open_university_learning_analytics_student_assessment_ds["score"] * open_university_learning_analytics_student_assessment_ds["weight"])/100
open_university_learning_analytics_student_assessment_ds.head()

,id_assessment,id_student,date_submitted,is_banked,score,code_module,code_presentation,assessment_type,date,weight,weighted_score
0,1752,11391,18,0,78.0,AAA,2013J,TMA,19,10.0,7.8
1,1752,28400,22,0,70.0,AAA,2013J,TMA,19,10.0,7.0
2,1752,31604,17,0,72.0,AAA,2013J,TMA,19,10.0,7.2
3,1752,32885,26,0,69.0,AAA,2013J,TMA,19,10.0,6.9
4,1752,38053,19,0,79.0,AAA,2013J,TMA,19,10.0,7.9

In [47]:
# Create an aggregated df which contains unique student id and their assessment mark summary
student_performance_aggregated_ds = open_university_learning_analytics_student_assessment_ds.groupby(["id_student"]).agg(
    total_weighted_score=('weighted_score', 'sum'),
    avg_score=('score', 'mean'),
    assessments_submitted=('id_assessment', 'count')
).reset_index()

student_performance_aggregated_ds.head()

   id_student  total_weighted_score  avg_score  assessments_submitted
0        6516                 63.50  61.800000                      5
1        8462                 77.90  87.000000                      7
2       11391                 82.40  82.000000                      5
3       23629                 16.69  82.500000                      4
4       23698                149.97  74.444444                      9

#### 3. Merge engagement and student engagement data sets

In [49]:
open_university_learning_analytics_student_vle_ds.dtypes

code_module          object
code_presentation    object
id_student            int64
id_site               int64
date                  int64
sum_click             int64
dtype: object

In [50]:
open_university_learning_analytics_vle_ds.dtypes

id_site               int64
code_module          object
code_presentation    object
activity_type        object
week_from            object
week_to              object
dtype: object